name: Saydaliati
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.15
  flutter_keyboard_visibility: ^5.0.0
  path: ^1.8.0
  url_launcher: ^6.0.9
  share_plus: ^4.0.10
  camera: ^0.10.5+9  
  http: ^0.13.3
  image_picker: ^0.8.4+3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.15.9
  google_sign_in: ^6.2.1
  firebase_analytics: ^10.8.10
  google_maps_flutter: ^2.5.3
  table_calendar: ^3.0.5

  flutter_email_sender: ^5.0.2
  adobe_xd: ^2.0.1
  awesome_notifications: ^0.7.4+1
  flutter_local_notifications: ^9.0.0
  intl: ^0.17.0
  provider: ^6.1.2
  shared_preferences: ^2.0.13
  flutter_launcher_icons: "^0.13.1"
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
